//int save_and_exit();
void write_rolo(FILE* fp1, FILE* fp2);
int cathelpfile (char *filepath, char *helptopic, int clear);
void clearinit();
void clear_the_screen();
void read_rolodex(int fd);
void user_eof();
int rlength(Ptr_Rolo_List rlist);
void rolo_reorder();
void print_short();
void print_people();
void interactive_rolo();
int rolo_menu_yes_no (char *prompt, int rtn_default, int help_allowed, char *helpfile, char *subject);